### ISSUE TITLE
玩家加入后报错

### ISSUE THREAD

**Issue by LinkTechTips** [TISUnion/Task#10]
`[MCDR] [07:36:14] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=mcd_task@2.3.2+build.64,priority=1000,callback=<function on_player_joined at 0x7f8eef2192d0>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/plugin/plugin_manager.py", line 494, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/plugin/plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins/Task-v2.3.2+build.64.mcdr/mcd_task/__init__.py", line 40, in on_player_joined
    task = GlobalVariables.task_manager[t].titles
  File "plugins/Task-v2.3.2+build.64.mcdr/mcd_task/task_manager.py", line 138, in __getitem__
    if titles.is_empty:
AttributeError: 'Task' object has no attribute 'is_empty'`

**Comment by Ra1ny-Yuki** [comment]
这似乎与现存的#9 issue 重复

**Comment by Ra1ny-Yuki** [comment]
新版本已尝试修复该问题，请尝试并确认该问题是否修复：https://github.com/TISUnion/Task/releases/tag/2.3.4

如可确认烦请在#9 issue下回复确认修复，如变动引发了新的未修复错误请另起issue
