### ISSUE TITLE
使用deadline报错

### ISSUE THREAD

**Issue by AbrasiveBoar902** [TISUnion/Task#8]
[MCDR] [11:46:11] [TaskExecutor/ERROR]: Error when executing command "!!task deadline" with command source "Player zijinshanren" on Literal[literals={'!!task'}] registered by mcd_task@2.0.1
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\site-packages\mcdreforged\translation\translation_manager.py", line 75, in translate
    translated_text = translated_text.format(*args, **kwargs)
IndexError: Replacement index 0 out of range for positional args tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\site-packages\mcdreforged\command\command_manager.py", line 70, in _traverse
    node.execute(source, command)
  File "D:\Program Files\Python39\lib\site-packages\mcdreforged\command\builder\nodes\basic.py", line 422, in execute
    self._execute_command(CommandContext(source, command))
  File "D:\Program Files\Python39\lib\site-packages\mcdreforged\command\builder\nodes\basic.py", line 335, in _execute_command
    child_literal._execute_command(context)
  File "D:\Program Files\Python39\lib\site-packages\mcdreforged\command\builder\nodes\basic.py", line 308, in _execute_command
    failure_message = self.__smart_callback(getter, context.source, context)
  File "D:\Program Files\Python39\lib\site-packages\mcdreforged\command\builder\nodes\basic.py", line 276, in __smart_callback
    return callback(*args[:spec_args_len])
  File "plugins\Task-v2.0.1.mcdr\mcd_task\command_actions.py", line 22, in <lambda>
    failure_message_getter=lambda: server.tr('mcd_task.perm_denied').format(lvl)
  File "D:\Program Files\Python39\lib\site-packages\mcdreforged\plugin\server_interface.py", line 90, in tr
    return self._mcdr_server.tr(translation_key, *args, language=language, **kwargs)
  File "D:\Program Files\Python39\lib\site-packages\mcdreforged\mcdr_server.py", line 145, in tr
    return self.translation_manager.translate(
  File "D:\Program Files\Python39\lib\site-packages\mcdreforged\translation\translation_manager.py", line 77, in translate
    raise ValueError('Failed to apply args {} and kwargs {} to translated_text {}: {}'.format(args, kwargs, translated_text, e))
ValueError: Failed to apply args () and kwargs {} to translated_text 权限不足, 你想桃子呢, 需要权限等级{}: Replacement index 0 out of range for positional args tuple

**Comment by Ra1ny-Yuki** [comment]
抱歉迟回，问题已定位，是权限报错文本的问题，理论上已在最后一次提交中修复，感谢报告，该问题可在该版本release后关闭（但是因为我暂时没有时间测试可能鸽一段时间）
