### ISSUE TITLE
后台时常报错

### ISSUE THREAD

**Issue by Pau1am** [TISUnion/Task#9]
[MCDR] [13:03:44] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=mcd_task@2.3.2+build.64,priority=1000,callback=<function on_player_joined at 0x000001B99C0D7370>]
Traceback (most recent call last):
  File "E:\MCDReforged-2.5.1\mcdreforged\plugin\plugin_manager.py", line 494, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "E:\MCDReforged-2.5.1\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins\[工程]Task-v2.3.2+build.64.mcdr\mcd_task\__init__.py", line 40, in on_player_joined
    task = GlobalVariables.task_manager[t].titles
  File "plugins\[工程]Task-v2.3.2+build.64.mcdr\mcd_task\task_manager.py", line 138, in __getitem__
    if titles.is_empty:
AttributeError: 'Task' object has no attribute 'is_empty'

**Comment by Ra1ny-Yuki** [comment]
触发条件已由#10确认为玩家加入时

**Comment by Ra1ny-Yuki** [comment]
新版本已尝试修复该问题，请尝试并确认该问题是否修复：https://github.com/TISUnion/Task/releases/tag/2.3.4

如可确认烦请关闭该issue，如变动引发了新的未修复错误请另起issue

**Comment by LinkTechTips** [comment]
> 新版本已尝试修复该问题，请尝试并确认该问题是否修复：https://github.com/TISUnion/Task/releases/tag/2.3.4
> 
> 如可确认烦请关闭该issue，如变动引发了新的未修复错误请另起issue

[v2.3.4+build.66](https://github.com/TISUnion/Task/releases/tag/2.3.4)已经解决了#10的问题
运行环境:
Linux-5.4.0-132-generic-x86_64-with-glibc2.31
Python3.10.8
[MCDReforged v2.6](https://github.com/Fallen-Breath/MCDReforged/releases/tag/v2.6.0)
